# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battleship.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61ttleship.proto\x12\nbattleship\"(\n\nInitialize\x12\x1a\n\x12g_captcha_response\x18\x01 \x02(\t\"\x14\n\x04\x46lag\x12\x0c\n\x04\x66lag\x18\x01 \x02(\t\"!\n\x05Point\x12\x0b\n\x03row\x18\x01 \x02(\r\x12\x0b\n\x03\x63ol\x18\x02 \x02(\r\",\n\x07Missile\x12!\n\x06target\x18\x01 \x02(\x0b\x32\x11.battleship.Point\"\x8f\x01\n\x04Ship\x12 \n\x05start\x18\x01 \x02(\x0b\x32\x11.battleship.Point\x12\x31\n\x0borientation\x18\x02 \x02(\x0e\x32\x1c.battleship.Ship.Orientation\x12\x0e\n\x06length\x18\x03 \x02(\r\"\"\n\x0bOrientation\x12\x08\n\x04\x44OWN\x10\x00\x12\t\n\x05RIGHT\x10\x01\"\x99\x01\n\rMissileResult\x12?\n\x0emissile_result\x18\x01 \x02(\x0e\x32\'.battleship.MissileResult.MissileResult\x12#\n\tship_sunk\x18\x02 \x01(\x0b\x32\x10.battleship.Ship\"\"\n\rMissileResult\x12\x07\n\x03HIT\x10\x00\x12\x08\n\x04MISS\x10\x01\"G\n\x05\x42oard\x12\r\n\x05width\x18\x01 \x02(\r\x12\x0e\n\x06height\x18\x02 \x02(\r\x12\x1f\n\x05ships\x18\x03 \x03(\x0b\x32\x10.battleship.Ship')



_INITIALIZE = DESCRIPTOR.message_types_by_name['Initialize']
_FLAG = DESCRIPTOR.message_types_by_name['Flag']
_POINT = DESCRIPTOR.message_types_by_name['Point']
_MISSILE = DESCRIPTOR.message_types_by_name['Missile']
_SHIP = DESCRIPTOR.message_types_by_name['Ship']
_MISSILERESULT = DESCRIPTOR.message_types_by_name['MissileResult']
_BOARD = DESCRIPTOR.message_types_by_name['Board']
_SHIP_ORIENTATION = _SHIP.enum_types_by_name['Orientation']
_MISSILERESULT_MISSILERESULT = _MISSILERESULT.enum_types_by_name['MissileResult']
Initialize = _reflection.GeneratedProtocolMessageType('Initialize', (_message.Message,), {
  'DESCRIPTOR' : _INITIALIZE,
  '__module__' : 'battleship_pb2'
  # @@protoc_insertion_point(class_scope:battleship.Initialize)
  })
_sym_db.RegisterMessage(Initialize)

Flag = _reflection.GeneratedProtocolMessageType('Flag', (_message.Message,), {
  'DESCRIPTOR' : _FLAG,
  '__module__' : 'battleship_pb2'
  # @@protoc_insertion_point(class_scope:battleship.Flag)
  })
_sym_db.RegisterMessage(Flag)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'battleship_pb2'
  # @@protoc_insertion_point(class_scope:battleship.Point)
  })
_sym_db.RegisterMessage(Point)

Missile = _reflection.GeneratedProtocolMessageType('Missile', (_message.Message,), {
  'DESCRIPTOR' : _MISSILE,
  '__module__' : 'battleship_pb2'
  # @@protoc_insertion_point(class_scope:battleship.Missile)
  })
_sym_db.RegisterMessage(Missile)

Ship = _reflection.GeneratedProtocolMessageType('Ship', (_message.Message,), {
  'DESCRIPTOR' : _SHIP,
  '__module__' : 'battleship_pb2'
  # @@protoc_insertion_point(class_scope:battleship.Ship)
  })
_sym_db.RegisterMessage(Ship)

MissileResult = _reflection.GeneratedProtocolMessageType('MissileResult', (_message.Message,), {
  'DESCRIPTOR' : _MISSILERESULT,
  '__module__' : 'battleship_pb2'
  # @@protoc_insertion_point(class_scope:battleship.MissileResult)
  })
_sym_db.RegisterMessage(MissileResult)

Board = _reflection.GeneratedProtocolMessageType('Board', (_message.Message,), {
  'DESCRIPTOR' : _BOARD,
  '__module__' : 'battleship_pb2'
  # @@protoc_insertion_point(class_scope:battleship.Board)
  })
_sym_db.RegisterMessage(Board)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITIALIZE._serialized_start=32
  _INITIALIZE._serialized_end=72
  _FLAG._serialized_start=74
  _FLAG._serialized_end=94
  _POINT._serialized_start=96
  _POINT._serialized_end=129
  _MISSILE._serialized_start=131
  _MISSILE._serialized_end=175
  _SHIP._serialized_start=178
  _SHIP._serialized_end=321
  _SHIP_ORIENTATION._serialized_start=287
  _SHIP_ORIENTATION._serialized_end=321
  _MISSILERESULT._serialized_start=324
  _MISSILERESULT._serialized_end=477
  _MISSILERESULT_MISSILERESULT._serialized_start=443
  _MISSILERESULT_MISSILERESULT._serialized_end=477
  _BOARD._serialized_start=479
  _BOARD._serialized_end=550
# @@protoc_insertion_point(module_scope)
